name: ddpg
mode: train
dataset:
  train_length: 49824
  sliding_window_size: 144
  sliding_window_offset: 24
  forecast_horizon: 47
policy:
  num_cells: [400,300]
ou:
  annealing_num_steps: 1000000
  n_steps_annealing: 1000000
critic:
  num_cells: [400,300]
collector_frames_per_batch: 100
replay_buffer_size: 100000
batch_size: 64
delay_actor: False
delay_value: True
gamma: 0.99
tau: 0.005
lr:
  actor: 1e-4
  value: 1e-3
val_interval: 10
early_stopping_patience: 2000
max_train_iterations:
state_estimator:
  n_frames: 12