name: ddpg
mode: train_half
dataset:
  sliding_window_size: 144
  sliding_window_offset: 24
  forecast_horizon: 32
policy:
  num_cells: [400,300]
ou:
  annealing_num_steps: 1000000
  n_steps_annealing: 1000000
critic:
  num_cells: [400,300]
collector_frames_per_batch: 100
replay_buffer_size: 100000
batch_size: 128
delay_actor: False
delay_value: True
gamma: 0.99
tau: 0.005
lr:
  actor: 1e-4
  value: 1e-3
val_interval: 10
early_stopping_patience: 2000