name: dt
mode: train
batch_size: 64
num_iterations: 3000
eval_interval: 10
max_context_length: 48
dataset:
  sliding_window_size: 1344
  sliding_window_offset: 1344
  forecast_horizon: 32
optimizer:
  lr: 1e-4
  weight_decay: 1e-4
transformer:
  num_heads: 4
  num_layers: 6
model_dim: 128
target_return:
  val:
  test:

