name: kd
mode: train
temp: 2
batch_size: 32
num_iterations: 1000
eval_interval: 10
max_context_length: 96
model_dim: 512
dataset:
  sliding_window_size: 1344
  sliding_window_offset: 1344
  forecast_horizon: 32
optimizer:
  lr: 1e-4
  weight_decay: 1e-4
soft_target_loss_weight: 0.25
ce_loss_weight: 0.75
teacher:
  model_dim: 512
  transformer:
    num_heads: 4
    num_layers: 6
student:
  model_dim: 128
  transformer:
    num_heads: 4
    num_layers: 6