name: kd
mode: train
batch_size: 32
num_iterations: 5000
val_interval: 50
max_context_length: 96
dataset:
  mode: global
  val_list: []
  sliding_window_size: 1344
  sliding_window_offset: 1344
  forecast_horizon: 24
optimizer:
  lr: 1e-4
teacher:
  path:
  model_dim: 128
  transformer:
    num_heads: 4
    num_layers: 6
student:
  model_dim: 128
  transformer:
    num_heads: 4
    num_layers: 3
target_return:
  val:
  test:
early_stopping_patience: 500