hydra:
  run:
    dir: ${output_path}/log/${name}
  sweep:
    dir: ${output_path}/log/${name}

name: firstRun
output_path: output
model_path: ${output_path}/model
log_path: ${output_path}/log
generated_data_path: ${output_path}/generated_data
raw_data_path: data/1_processed
use_pretrained: False
forecast_horizon: 12
seed: 42
device: cpu
