hydra:
  run:
    dir: ${output_path}

defaults:
  - component: ddpg
  - _self_

name: 
output_path: ../output/${component.name}/${component.mode}/${building_id}/${name}
model_path: ../model/${component.name}/${component.mode}/${building_id}/${name}
raw_data_path: ../data/1_processed
generated_data_path: ../data/2_generated

building_id: 13
seed: 42
device: cpu