hydra:
  run:
    dir: ${output_path}

defaults:
  - component: ddpg
  - _self_

name: run0
output_path: ../output/${component.name}/${customer}/${name}
model_path: ../model/${component.name}/${customer}/${name}
raw_data_path: ../data/1_processed
generated_data_path: ../data/2_generated

customer: 13
seed: 42
device: cpu